name: Backup Script Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-backup-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gpg
          sudo apt-get install -y cron
          sudo apt-get install -y util-linux # For lsblk and mount commands

      - name: Create backup config file
        run: |
          echo "backup_option=\"1\"" >> backup_config
          echo "backup_dir=\"/tmp/backup\"" >> backup_config
          echo "mount_option=\"n\"" >> backup_config
          echo "data_options=\"1\"" >> backup_config
          echo "encrypt_option=\"n\"" >> backup_config 
  
      - name: Test running the backup manually
        run: |
          chmod +x backup.sh
          ./backup.sh

      - name: Test backup directory creation
        run: |
          if [ ! -d "/tmp/backup" ]; then
            echo "Backup directory was not created!"
            exit 1
          fi
          echo "Backup directory exists."
      
      - name: Test scheduling the cron job
        run: |
          rm -f backup_config
          echo "backup_option=\"2\"" >> backup_config
          echo "cron_frequency=\"weekly\"" >> backup_config
          chmod +x backup.sh
          ./backup.sh
          # Check if cron job is added
          crontab -l | grep "backup.sh"

      - name: Clean up
        run: |
          rm -rf /tmp/backup
